Repository meituan/EasyReact, pull requests merged in 2018-07, with the labels that each got.

#5 config fastlane
  .travis.yml
  Example/Podfile.lock
  Gemfile
  Gemfile.lock
  README-Chinese.md
  README.md
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/codecov.rb
Labels: Feature

#7 <perf>(<location>) : <run benchmark again using iOS device>
  Example/Benchmark/Target/EZRBenchmarkTarget.m
  README-Chinese.md
  README.md
  images/benchmark.png
Labels: Question

#12 Fix a typo.
  CONTRIBUTING.md
Labels: Good first issue, Typo

#15 fix(location) : fix EZRPath KVO crash
  EasyReact/Classes/Utils/EZRPathTrampoline.m
  Example/Tests/NSObject+ER_Extension.m
  Gemfile.lock
Labels: Bug

#18 Fix: memory management spelling mistake
  Documents/Chinese/MemoryManagement.md
  Documents/English/MemoryManagement.md
Labels: Typo

#23 Fix:fix some words typos
  Documents/Chinese/BasicOperators.md
Labels: Typo

#25 fix(location) : fix listenEdge delay dealloc
  CHANGELOG.md
  EasyReact/Classes/Core/EZRListenContext.m
  Example/Podfile.lock
Labels: Bug

#29 feat : add EZRPerformSelectorListen edge
  CHANGELOG.md
  Documents/Chinese/BasicOperators.md
  Documents/English/BasicOperators.md
  EasyReact/Classes/Core/EZRListenContext.h
  EasyReact/Classes/Core/EZRListenContext.m
  EasyReact/Classes/Core/ListenEdges/EZRPerformSelectorListen.h
  EasyReact/Classes/Core/ListenEdges/EZRPerformSelectorListen.m
  Example/EasyReact.xcodeproj/project.pbxproj
  Example/Podfile
  Example/Podfile.lock
  Example/Tests/EZRListenContextSpec.m
  Example/Tests/TestSupportClasses/Matchers/CustomMatchers.m
  Example/Tests/TestSupportClasses/Matchers/hasAssert.swift
  Example/Tests/TestSupportClasses/TestListener.h
  Example/Tests/TestSupportClasses/TestListener.m
  Example/Tests/Tests-Prefix.pch
Labels: Feature
