Repository meituan/EasyReact, pull requests merged in 2018-08, with the labels that each got.

#37 Update documents.
  Documents/Chinese/BasicOperators.md
  Documents/Chinese/MemoryManagement.md
  Documents/English/BasicOperators.md
Labels: Bug, Good first issue, Typo

#36 Optimize code
  EasyReact/Classes/Core/EZRMutableNode.m
  EasyReact/Classes/Core/NodeTransforms/EZRCaseTransform.m
  EasyReact/Classes/Core/NodeTransforms/EZRSwitchMapTransform.m
  Example/Tests/EZRNode+Operation.m
Labels: Bug, Feature

#35 fix syncWith:transform:revert implementation
  EasyReact/Classes/Core/EZRNode+Operation.h
  EasyReact/Classes/Core/EZRNode+Operation.m
  EasyReact/Classes/Utils/EZRPathTrampoline.m
  Example/Tests/EZRNode+Operation.m
Labels: Bug

#44 fix document errors
  Documents/Chinese/MemoryManagement.md
  Documents/English/MemoryManagement.md
Labels: Good first issue, Typo

#50 fix(location) : keep code style consistent and fix some typos.
  EasyReact/Classes/Categories/NSObject+EZR_Extension.h
  EasyReact/Classes/Categories/NSObject+EZR_Extension.m
  EasyReact/Classes/Core/EZRBlockCancelable.h
  EasyReact/Classes/Core/EZRCancelable.h
  EasyReact/Classes/Core/EZRCancelableBag.h
  EasyReact/Classes/Core/EZRCancelableBagProtocol.h
  EasyReact/Classes/Core/EZREdge.h
  EasyReact/Classes/Core/EZREmpty.h
  EasyReact/Classes/Core/EZRListenContext.h
  EasyReact/Classes/Core/EZRListenContext.m
  EasyReact/Classes/Core/EZRListenEdge.h
  EasyReact/Classes/Core/EZRMetaMacros.h
  EasyReact/Classes/Core/EZRNode+Graph.h
  EasyReact/Classes/Core/EZRNode+Graph.m
  EasyReact/Classes/Core/EZRNode+Mutable.h
  EasyReact/Classes/Core/EZRNode+Operation.h
  EasyReact/Classes/Core/EZRNode+Traversal.h
  EasyReact/Classes/Core/EZRNode.h
  EasyReact/Classes/Core/EZRNode.m
  EasyReact/Classes/Core/EZRTransform.h
  EasyReact/Classes/Core/EZRTransformEdge.h
  EasyReact/Classes/Core/ListenEdges/EZRPerformSelectorListen.m
  EasyReact/Classes/Core/NSObject+EZR_Listen.h
  EasyReact/Classes/Core/NSObject+EZR_Listen.m
  EasyReact/Classes/Core/NodeTransforms/EZRCombineTransform.m
  EasyReact/Classes/Core/NodeTransforms/EZRFlattenTransform.h
  EasyReact/Classes/Core/NodeTransforms/EZRFlattenTransform.m
  EasyReact/Classes/Core/Private/EZRMetaMacrosPrivate.h
  EasyReact/Classes/Utils/EZRPathTrampoline.m
Labels: Typo

#51 feat(document) : add relation document links to README-Chinese.md
  README-Chinese.md
Labels: Document
